language: android
jdk:
        - oraclejdk8
android:
        components:
                - tools
                - tools
                - platform-tools
                - build-tools-26.0.1
                - android-26
                - extra-android-support
                - sys-img-armeabi-v7a-android-26

