language: android
jdk:
  - oraclejdk8

env:
        global:
                - COMPILE_SDK_VERSION = 25
                - BUILD_TOOLS_VERSION = 25.0.3

android:
        components:
                - tools
                - platform-tools
                - tools
                - build-tools-$BUILD_TOOLS_VERSION
                - android-$COMPILE_SDK_VERSION
                - extra-android-support
        licenses:
                - android-sdk-license-.+
script:
        - "./gradlew build connectedCheck"

