language: android
jdk:
  - oraclejdk8

env:
  global:
    - COMPILE_SDK_VERSION = 26
    - BUILD_TOOLS_VERSION = 26.0.1

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$COMPILE_SDK_VERSION
    - extra-android-support

script:
  - "./gradlewbuild connectedCheck

