language: android
jdk:
        - oraclejdk8
android:
        components:
                - tools
                - tools
                - platform-tools
                - build-tools-26.0.1
                - android-25
                - extra-android-support
